name = "GenieSession"
uuid = "03cc5b98-4f21-4eb6-99f2-22eced81f962"
authors = ["Adrian Salceanu <adrian.salceanu@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
